export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_ADDRESS_DATA = "GET_ADDRESS_DATA";
export const GET_LISTVIEW_DATA = "GET_LISTVIEW_DATA";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

//Add Product

//step1
export const FETCH_BRAND_REQUEST = "FETCH_BRAND_REQUEST";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_FAILURE = "FETCH_BRAND_FAILURE";

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";

export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAILURE = "UPDATE_BRAND_FAILURE";

export const FETCH_CONDITION_REQUEST = "FETCH_CONDITION_REQUEST";
export const FETCH_CONDITION_SUCCESS = "FETCH_CONDITION_SUCCESS";
export const FETCH_CONDITION_FAILURE = "FETCH_CONDITION_FAILURE";

export const FETCH_PRODUCTTYPE_REQUEST = "FETCH_PRODUCTTYPE_REQUEST";
export const FETCH_PRODUCTTYPE_SUCCESS = "FETCH_PRODUCTTYPE_SUCCESS";
export const FETCH_PRODUCTTYPE_FAILURE = "FETCH_PRODUCTTYPE_FAILURE";

export const FETCH_STDPRODUCTTYPE_REQUEST = "FETCH_PRODUCTTYPE_REQUEST";
export const FETCH_STDPRODUCTTYPE_SUCCESS = "FETCH_STDPRODUCTTYPE_SUCCESS";
export const FETCH_STDPRODUCTTYPE_FAILURE = "FETCH_STDPRODUCTTYPE_FAILURE";

export const FETCH_PROCUREMENT_REQUEST = "FETCH_PROCUREMENT_REQUEST";
export const FETCH_PROCUREMENT_SUCCESS = "FETCH_PROCUREMENT_SUCCESS";
export const FETCH_PROCUREMENT_FAILURE = "FETCH_PROCUREMENT_FAILURE";

export const FETCH_ROUTES_REQUEST = "FETCH_ROUTES_REQUEST";
export const FETCH_ROUTES_SUCCESS = "FETCH_ROUTES_SUCCESS";
export const FETCH_ROUTES_FAILURE = "FETCH_ROUTES_FAILURE";

export const FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST";
export const FETCH_INVENTORY_SUCCESS = "FETCH_INVENTORY_SUCCESS";
export const FETCH_INVENTORY_FAILURE = "FETCH_INVENTORY_FAILURE";

export const FETCH_BASEUOM_REQUEST = "FETCH_BASEUOM_REQUEST";
export const FETCH_BASEUOM_SUCCESS = "FETCH_BASEUOM_SUCCESS";
export const FETCH_BASEUOM_FAILURE = "FETCH_BASEUOM_FAILURE";

export const FETCH_PARENT_CATEGORY_REQUEST = "FETCH_PARENT_CATEGORY_REQUEST";
export const FETCH_PARENT_CATEGORY_SUCCESS = "FETCH_PARENT_CATEGORY_SUCCESS";
export const FETCH_PARENT_CATEGORY_FAILURE = "FETCH_PARENT_CATEGORY_FAILURE";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

//step2

export const FETCH_ATTRIBUTE_REQUEST = "FETCH_ATTRIBUTE_REQUEST";
export const FETCH_ATTRIBUTE_SUCCESS = "FETCH_ATTRIBUTE_SUCCESS";
export const FETCH_ATTRIBUTE_FAILURE = "FETCH_ATTRIBUTE_FAILURE";

export const CREATE_ATTRIBUTE_REQUEST = "CREATE_ATTRIBUTE_REQUEST";
export const CREATE_ATTRIBUTE_SUCCESS = "CREATE_ATTRIBUTE_SUCCESS";
export const CREATE_ATTRIBUTE_FAILURE = "CREATE_ATTRIBUTE_FAILURE";

export const FETCH_PROPERTY_REQUEST = "FETCH_PROPERTY_REQUEST";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS";
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";

export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";

export const CREATE_VARIANT_REQUEST = "CREATE_VARIANT_REQUEST";
export const CREATE_VARIANT_SUCCESS = "CREATE_VARIANT_SUCCESS";
export const CREATE_VARIANT_FAILURE = "CREATE_VARIANT_FAILURE";
//step 3

export const CHECK_MRP_REQUEST = "CHECK_MRP_REQUEST";
export const CHECK_MRP_SUCCESS = "CHECK_MRP_SUCCESS";
export const CHECK_MRP_FAILURE = "CHECK_MRP_FAILURE";

export const FETCH_VENDOR_REQUEST = "FETCH_VENDOR_REQUEST";
export const FETCH_VENDOR_SUCCESS = "FETCH_VENDOR_SUCCESS";
export const FETCH_VENDOR_FAILURE = "FETCH_VENDOR_FAILURE";

export const FETCH_PRODUCTPACKAGE_REQUEST = "FETCH_PRODUCTPACKAGE_REQUEST";
export const FETCH_PRODUCTPACKAGE_SUCCESS = "FETCH_PRODUCTPACKAGE_SUCCESS";
export const FETCH_PRODUCTPACKAGE_FAILURE = "FETCH_PRODUCTPACKAGE_FAILURE";

export const FETCH_VENDORPRICELIST_REQUEST = "FETCH_VENDORPRICELIST_REQUEST";
export const FETCH_VENDORPRICELIST_SUCCESS = "FETCH_VENDORPRICELIST_SUCCESS";
export const FETCH_VENDORPRICELIST_FAILURE = "FETCH_VENDORPRICELIST_FAILURE";

export const FETCH_SHIPPINGPARTNER_REQUEST = "FETCH_SHIPPINGPARTNER_REQUEST";
export const FETCH_SHIPPINGPARTNER_SUCCESS = "FETCH_SHIPPINGPARTNER_SUCCESS";
export const FETCH_SHIPPINGPARTNER_FAILURE = "FETCH_SHIPPINGPARTNER_FAILURE";

export const FETCH_SHIPPINGPARTNERVIEW_REQUEST =
  "FETCH_SHIPPINGPARTNERVIEW_REQUEST";
export const FETCH_SHIPPINGPARTNERVIEW_SUCCESS =
  "FETCH_SHIPPINGPARTNERVIEW_SUCCESS";
export const FETCH_SHIPPINGPARTNERVIEW_FAILURE =
  "FETCH_SHIPPINGPARTNERVIEW_FAILURE";

export const CREATE_VP_REQUEST = "CREATE_VP_REQUEST";
export const CREATE_VP_SUCCESS = "CREATE_VP_SUCCESS";
export const CREATE_VP_FAILURE = "CREATE_VP_FAILURE";
//

//ProductsView

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

//

//ProductsEdit

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const EDIT_VARIANT_IMAGES_REQUEST = "EDIT_VARIANT_IMAGES_REQUEST";
export const EDIT_VARIANT_IMAGES_SUCCESS = "EDIT_VARIANT_IMAGES_SUCCESS";
export const EDIT_VARIANT_IMAGES_FAILURE = "EDIT_VARIANT_IMAGES_FAILURE";

//

export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_FAILURE = "FETCH_COUNTRY_FAILURE";

export const GET_PRODUCT_ID = "GET_PRODUCT_ID";

export const FETCH_PRODUCT_BY_ID_REQUEST = "FETCH_PRODUCT_BY_ID_REQUEST";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_FAILURE = "FETCH_PRODUCT_BY_ID_FAILURE";

export const FETCH_STATE_FAILURE = "FETCH_STATE_FAILURE";
export const FETCH_STATE = "FETCH_STATE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const FAVOURITE_PRODUCT_REQUEST = "FAVOURITE_PRODUCT_REQUEST";
export const FAVOURITE_PRODUCT_SUCCESS = "FAVOURITE_PRODUCT_SUCCESS";
export const FAVOURITE_PRODUCT_FAILURE = "FAVOURITE_PRODUCT_FAILURE";

export const ARCHIVE_PRODUCT_REQUEST = "ARCHIVE_PRODUCT_REQUEST";
export const ARCHIVE_PRODUCT_SUCCESS = "ARCHIVE_PRODUCT_SUCCESS";
export const ARCHIVE_PRODUCT_FAILURE = "ARCHIVE_PRODUCT_FAILURE";

//search redux
export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";

export const FETCH_CUSTOM_REQUEST = "FETCH_CUSTOM_REQUEST";
export const FETCH_CUSTOM_SUCCESS = "FETCH_CUSTOM_SUCCESS";
export const FETCH_CUSTOM_FAILURE = "FETCH_CUSTOM_FAILURE";

export const FETCH_CURRENCY_REQUEST = "FETCH_CURRENCY_REQUEST";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAILURE = "FETCH_CURRENCY_FAILURE";

//session
export const GET_SESSION_ID = "GET_SESSION_ID";
export const GET_TOKEN_SUCCESSS = "GET_TOKEN_SUCCESSS";

export const FETCH_AVAILABLE_MARKETPLACE_REQUEST = "FETCH_AVAILABLE_MARKETPLACE_REQUEST";
export const FETCH_AVAILABLE_MARKETPLACE_SUCCESS = "FETCH_AVAILABLE_MARKETPLACE_SUCCESS";
export const FETCH_AVAILABLE_MARKETPLACE_FAILURE = "FETCH_AVAILABLE_MARKETPLACE_FAILURE";

export const FETCH_ACCESS_MANAGEMENT_REQUEST = "FETCH_ACCESS_MANAGEMENT_REQUEST";
export const FETCH_ACCESS_MANAGEMENT_SUCCESS = "FETCH_ACCESS_MANAGEMENT_SUCCESS";
export const FETCH_ACCESS_MANAGEMENT_FAILURE = "FETCH_ACCESS_MANAGEMENT_FAILURE";


//combined
export const PRICING_VIEW_DATA = "PRICING_VIEW_DATA";
export const PURCHASE_RETURNS_DATA = "PURCHASE_RETURNS_DATA";
export const SALES_RETURNS_DATA = "SALES_RETURNS_DATA";
export const SALES_HISTORY_DATA = "SALES_HISTORY_DATA";
export const PRODUCT_BUNDLE_VIEW_DATA = "PRODUCT_BUNDLE_VIEW_DATA";

/*
 Copyright (C) 2022 Eunimart Omnichannel Pvt Ltd. (www.eunimart.com)
 All rights reserved.
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License v3.0 as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License v3.0 for more details.
 You should have received a copy of the GNU Lesser General Public License v3.0
 along with this program.  If not, see <https://www.gnu.org/licenses/lgpl-3.0.html/>.
*/