export const IST_LIST = "IST_LIST";
export const IST_VIEW = "IST_VIEW";
export const COUNTRY_LIST = "COUNTRY_LIST";
export const STATE_LIST = "STATE_LIST";
export const SAVE_IST = "SAVE_IST";
export const UPDATE_IST = "UPDATE_IST";
export const IST_DELETE_LIST = "IST_DELETE_LIST";
export const ESTIMATED_COST_SUCCESS = "ESTIMATED_COST_SUCCESS";
export const ESTIMATED_COST_FAILURE = "ESTIMATED_COST_FAILURE";
export const IST_DATA_BY_ID = "IST_DATA_BY_ID";

// Sales Order
// Fetch
export const FETCH_SALES_ORDER_REQUEST = "FETCH_SALES_ORDER_REQUEST";
export const FETCH_SALES_ORDER_SUCCESS = "FETCH_SALES_ORDER_SUCCESS";
export const FETCH_SALES_ORDER_FAILURE = "FETCH_SALES_ORDER_FAILURE";

// Create
export const CREATE_SALES_ORDER_SUCCESS = "CREATE_SALES_ORDER_SUCCESS";

// Get ID
export const GET_SALES_ORDER_ID = "GET_SALES_ORDER_ID";

// Fetch By ID
export const FETCH_SALES_ORDER_BY_ID_REQUEST =
  "FETCH_SALES_ORDER_BY_ID_REQUEST";
export const FETCH_SALES_ORDER_BY_ID_SUCCESS =
  "FETCH_SALES_ORDER_BY_ID_SUCCESS";
export const FETCH_SALES_ORDER_BY_ID_FAILURE =
  "FETCH_SALES_ORDER_BY_ID_FAILURE";

// VendorID
export const VENDOR_SEARCH = "VENDOR_SEARCH";

// ASN
// Fetch
export const FETCH_ASN_DATA_SUCCESS = "FETCH_ASN_DATA_SUCCESS";
export const FETCH_ASN_DATA_FAIL = "FETCH_ASN_DATA_FAIL";

// Fetch By ID
export const FETCH_ASN_DATA_BY_ID_SUCCESS = "FETCH_ASN_DATA_BY_ID_SUCCESS";
export const FETCH_ASN_DATA_BY_ID_FAIL = "FETCH_ASN_DATA_BY_ID_FAIL";

// Create
export const CREATE_ASN_SUCCESS = "CREATE_ASN_SUCCESS";
export const CREATE_ASN_FAIL = "CREATE_ASN_FAIL";

export const EDIT_ASN_SUCCESS = "EDIT_ASN_SUCCESS";
export const EDIT_ASN_FAIL = "EDIT_ASN_FAIL";

export const FETCH_SALES_RETURNS_SUCCESS = "FETCH_SALES_RETURNS_SUCCESS";
export const FETCH_SALES_RETURNS_FAILURE = "FETCH_SALES_RETURNS_FAILURE";

export const ASN_SEARCH = "ASN_SEARCH";

export const ASN_DELETE_SUCCESS = "ASN_DELETE_SUCCESS";
export const ASN_DELETE_FAILURE = "ASN_DELETE_FAILURE";

// Search PO
export const SEARCH_PO = "SEARCH_PO";

// Product
// Fetch
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

// PO
export const PO_BY_ID_SUCCESS = "PO_BY_ID_SUCCESS";
export const PO_BY_ID_FAIL = "PO_BY_ID_FAIL";

export const GET_TEXT = "GET_TEXT";

// Location
export const SEARCH_LOCATION = "SEARCH_LOCATION";

export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";

export const FETCH_LOCATION_BY_ID_SUCCESS = "FETCH_LOCATION_BY_ID_SUCCESS";
export const FETCH_LOCATION_BY_ID_FAIL = "FETCH_LOCATION_BY_ID_FAIL";

export const FETCH_DISPATCH_LOCATION_BY_ID_SUCCESS =
  "FETCH_DISPATCH_LOCATION_BY_ID_SUCCESS";
export const FETCH_DISPATCH_LOCATION_BY_ID_FAIL =
  "FETCH_DISPATCH_LOCATION_BY_ID_FAIL";
export const FETCH_DELIVERY_LOCATION_BY_ID_SUCCESS =
  "FETCH_DELIVERY_LOCATION_BY_ID_SUCCESS";
export const FETCH_DELIVERY_LOCATION_BY_ID_FAIL =
  "FETCH_DELIVERY_LOCATION_BY_ID_FAIL";

export const SCRAP_SUCCESS = "SCRAP_SUCCESS";
export const SCRAP_FAILURE = "SCRAP_FAILURE";

export const GRN_SUCCESS = "GRN_SUCCESS";
export const GRN_FAILURE = "GRN_FAILURE";

export const GRN_SEARCH = "GRN_SEARCH";

export const RESET_PO_DATA_BY_ID = "RESET_PO_DATA_BY_ID";
export const RESET_SR_DATA_BY_ID = "RESET_SR_DATA_BY_ID";

export const SCRAP_SEARCH = "SCRAP_SEARCH";

export const SALES_RETURNS_SEARCH = "SALES_RETURNS_SEARCH";

export const FETCH_SALES_RETURNS_BY_ID_SUCCESS =
  "FETCH_SALES_RETURNS_BY_ID_SUCCESS";
export const FETCH_SALES_RETURNS_BY_ID_FAILURE =
  "FETCH_SALES_RETURNS_BY_ID_FAILURE";

export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAIL = "API_CALL_FAIL";

export const API_CALL_RESET = "API_CALL_RESET";
export const GET_SESSION_ID = "GET_SESSION_ID";

export const GET_SALES_RETUNS_LIST_REQUEST = "GET_SALES_RETUNS_LIST_REQUEST";
export const GET_SALES_RETUNS_LIST_SUCCESS = "GET_SALES_RETUNS_LIST_SUCCESS";
export const GET_SALES_RETUNS_LIST_FAILURE = "GET_SALES_RETUNS_LIST_FAILURE";

//Source Document
export const FETCH_SOURCE_DOCUMENT_DATA_SUCCESS =
  "FETCH_SOURCE_DOCUMENT_DATA_SUCCESS";
export const FETCH_SOURCE_DOCUMENT_DATA_FAILURE =
  "FETCH_SOURCE_DOCUMENT_DATA_FAILURE";

//Search Source Document
export const FETCH_SEARCH_SOURCE_DOCUMENT_DATA_SUCCESS =
  "FETCH_SEARCH_SOURCE_DOCUMENT_DATA_SUCCESS";
export const FETCH_SEARCH_SOURCE_DOCUMENT_DATA_FAILURE =
  "FETCH_SEARCH_SOURCE_DOCUMENT_DATA_FAILURE";

//Products list
export const FETCH_PRODUCTS_DATA_SUCCESS = "FETCH_PRODUCTS_DATA_SUCCESS";
export const FETCH_PRODUCTS_DATA_FAILURE = "FETCH_PRODUCTS_DATA_FAILURE";

//Price list
export const FETCH_PRICING_DATA_SUCCESS = "FETCH_PRICING_DATA_SUCCESS";
export const FETCH_PRICING_DATA_FAILURE = "FETCH_PRICING_DATA_FAILURE";

//UOM
export const FETCH_UOM_SUCCESS = "FETCH_UOM_SUCCESS";
export const FETCH_UOM_FAILURE = "FETCH_UOM_FAILURE";

//Lookups
export const FETCH_LOOKUPS_SUCCESS = "FETCH_LOOKUPS_SUCCESS";
export const FETCH_LOOKUPS_FAILURE = "FETCH_LOOKUPS_FAILURE";

//Lookups Routing
export const FETCH_LOOKUPSROUTING_SUCCESS = "FETCH_LOOKUPSROUTING_SUCCESS";
export const FETCH_LOOKUPSROUTING_FAILURE = "FETCH_LOOKUPSROUTING_FAILURE";

//Package Type
export const FETCH_PACKAGE_TYPE_SUCCESS = "FETCH_PACKAGE_TYPE_SUCCESS";
export const FETCH_PACKAGE_TYPE_FAILURE = "FETCH_PACKAGE_TYPE_FAILURE";

export const FETCH_PRICING_DATA_BY_ID_SUCCESS =
  "FETCH_PRICING_DATA_BY_ID_SUCCESS";
export const FETCH_PRICING_DATA_BY_ID_FAILURE =
  "FETCH_PRICING_DATA_BY_ID_FAILURE";

// Create PDF
export const DOWNLOAD_PDF_SUCCESS = "DOWNLOAD_PDF_SUCCESS";
export const DOWNLOAD_PDF_FAIL = "DOWNLOAD_PDF_FAIL";

// Email
export const EMAIL_SUCCESS = "EMAIL_SUCCESS";
export const EMAIL_FAIL = "EMAIL_FAIL";

// Favorite
export const FAV_SUCCESS = "FAV_SUCCESS";
export const FAV_FAIL = "FAV_FAIL";

// locations
export const FETCH_LOCATION_DATA_SUCCESS = "FETCH_LOCATION_DATA_SUCCESS";
export const FETCH_LOCATION_DATA_FAIL = "FETCH_LOCATION_DATA_FAIL";

export const FETCH_SCRAP_DATA_SUCCESS = "FETCH_SCRAP_DATA_SUCCESS";
export const FETCH_SCRAP_DATA_FAIL = "FETCH_SCRAP_DATA_FAIL";

export const SHIPPING_SUCCESS = "SHIPPING_SUCCESS";
export const SHIPPING_FAIL = "SHIPPING_FAIL";

export const STATES_SUCCESS = "STATES_SUCCESS";
export const STATES_FAILURE = "STATES_FAILURE";

export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAILURE = "COUNTRIES_FAILURE";

export const FETCH_LOCATION_DATA_BY_ID_SUCCESS =
  "FETCH_LOCATION_DATA_BY_ID_SUCCESS";

export const FETCH_LOCATION_TYPE_DATA_SUCCESS =
  "FETCH_LOCATION_TYPE_DATA_SUCCESS";
export const FETCH_LOCATION_TYPE_DATA_FAILURE =
  "FETCH_LOCATION_TYPE_DATA_FAILURE";

export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const CREATE_LOCATION_FAILURE = "CREATE_LOCATION_FAILURE";

export const GET_TOKEN_SUCCESSS = "GET_TOKEN_SUCCESSS";

// ASN
export const ASN_LIST = "ASN_LIST";
export const ASN_VIEW = "ASN_VIEW";
export const ASN_DATA_LIST = "ASN_DATA_LIST";

export const ASN_SUCCESS = "ASN_SUCCESS";
export const ASN_FAILURE = "ASN_FAILURE";

// Sales Orders
export const SALES_LIST = "SALES_LIST";
export const SALES_VIEW = "SALES_VIEW";
export const SALES_ORDERS_DATA_LIST = "SALES_DATA_LIST";

export const SALES_ORDERS_SUCCESS = "SALES_ORDERS_SUCCESS";
export const SALES_ORDERS_FAILURE = "SALES_ORDERS_FAILURE";
export const SALES_ORDERS_SEARCH = "SALES_ORDERS_SEARCH";

// Delivery Orders
export const DELIVERY_LIST = "DELIVERY_LIST";
export const DELIVERY_VIEW = "DELIVERY_VIEW";
export const DELIVERY_ORDERS_DATA_LIST = "DELIVERY_DATA_LIST";

export const DELIVERY_ORDERS_SUCCESS = "DELIVERY_ORDERS_SUCCESS";
export const DELIVERY_ORDERS_FAILURE = "DELIVERY_ORDERS_FAILURE";
export const DELIVERY_ORDERS_SEARCH = "DELIVERY_ORDERS_SEARCH";

// Purchase Orders
export const PURCHASE_ORDERS_LIST = "PURCHASE_ORDERS_LIST";
export const PURCHASE_ORDERS_LIST_BY_ID = "PURCHASE_ORDERS_LIST_BY_ID";
export const PURCHASE_ORDERS_DATA_LIST = "PURCHASE_ORDERS_DATA_LIST";

export const PURCHASE_ORDERS_SUCCESS = "PURCHASE_ORDERS_SUCCESS";
export const PURCHASE_ORDERS_FAILURE = "PURCHASE_ORDERS_FAILURE";
export const PURCHASE_ORDERS_SEARCH = "PURCHASE_ORDERS_SEARCH";

//GRN
export const GRN_LIST = "GRN_LIST";
export const GRN_DATA_BY_ID = "GRN_DATA_BY_ID";
export const GRN_DATA_LIST = "GRN_DATA_LIST";

//Access Mangement
export const ACCESS_MANAGEMENT = "ACCESS_MANAGEMENT";

//Delete Product Lines
export const DELETE_PRODUCT_LINE = "DELETE_PRODUCT_LINE";

/*			
Copyright (C) 2022 Eunimart Omnichannel Pvt Ltd. (www.eunimart.com)			
All rights reserved.			
This program is free software: you can redistribute it and/or modify			
it under the terms of the GNU General Public License as published by			
the Free Software Foundation, either version 3 of the License, or			
(at your option) any later version.			
This program is distributed in the hope that it will be useful,			
but WITHOUT ANY WARRANTY; without even the implied warranty of			
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the			
GNU General Public License for more details.			
You should have received a copy of the GNU General Public License			
along with this program. If not, see <http://www.gnu.org/licenses/>.			
*/
