export const GET_PRODUCT_DATA = "GET_PRODUCT_DATA";
export const GET_ADDRESS_DATA = "GET_ADDRESS_DATA";
export const GET_LISTVIEW_DATA = "GET_LISTVIEW_DATA";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

//Add Product

//create
export const FETCH_ITEMTYPE_REQUEST = "FETCH_ITEMTYPE_REQUEST";
export const FETCH_ITEMTYPE_SUCCESS = "FETCH_ITEMTYPE_SUCCESS";
export const FETCH_ITEMTYPE_FAILURE = "FETCH_ITEMTYPE_FAILURE";

export const FETCH_CLASSCODE_REQUEST = "FETCH_CLASSCODE_REQUEST";
export const FETCH_CLASSCODE_SUCCESS = "FETCH_CLASSCODE_SUCCESS";
export const FETCH_CLASSCODE_FAILURE = "FETCH_CLASSCODE_FAILURE";

export const FETCH_CLASSBASE_REQUEST = "FETCH_CLASSBASE_REQUEST";
export const FETCH_CLASSBASE_SUCCESS = "FETCH_CLASSBASE_SUCCESS";
export const FETCH_CLASSBASE_FAILURE = "FETCH_CLASSBASE_FAILURE";

export const FETCH_CONVERSIONTYPE_REQUEST = "FETCH_CONVERSIONTYPE_REQUEST";
export const FETCH_CONVERSIONTYPE_SUCCESS = "FETCH_CONVERSIONTYPE_SUCCESS";
export const FETCH_CONVERSIONTYPE_FAILURE = "FETCH_CONVERSIONTYPE_FAILURE";

export const CREATE_UOM_REQUEST = "CREATE_UOM_REQUEST";
export const CREATE_UOM_SUCCESS = "CREATE_UOM_SUCCESS";
export const CREATE_UOM_FAILURE = "CREATE_UOM_FAILURE";

export const CREATE_UOMCLASS_REQUEST = "CREATE_UOMCLASS_REQUEST";
export const CREATE_UOMCLASS_SUCCESS = "CREATE_UOMCLASS_SUCCESS";
export const CREATE_UOMCLASS_FAILURE = "CREATE_UOMCLASS_FAILURE";

//view
export const FETCH_UOM_REQUEST = "FETCH_UOM_REQUEST";
export const FETCH_UOM_SUCCESS = "FETCH_UOM_SUCCESS";
export const FETCH_UOM_FAILURE = "FETCH_UOM_FAILURE";

export const FETCH_UOMCLASS_REQUEST = "FETCH_UOMCLASS_REQUEST";
export const FETCH_UOMCLASS_SUCCESS = "FETCH_UOMCLASS_SUCCESS";
export const FETCH_UOMCLASS_FAILURE = "FETCH_UOMCLASS_FAILURE";

//update

export const FETCH_EDITUOM_REQUEST = "FETCH_EDITUOM_REQUEST";
export const FETCH_EDITUOM_SUCCESS = "FETCH_EDITUOM_SUCCESS";
export const FETCH_EDITUOM_FAILURE = "FETCH_EDITUOM_FAILURE";

export const UPDATEUOM_REQUEST = "UPDATEUOM_REQUEST";
export const UPDATEUOM_SUCCESS = "UPDATEUOM_SUCCESS";
export const UPDATEUOM_FAILURE = "UPDATEUOM_FAILURE";

export const UPDATEUOMCLASS_REQUEST = "UPDATEUOMCLASS_REQUEST";
export const UPDATEUOMCLASS_SUCCESS = "UPDATEUOMCLASS_SUCCESS";
export const UPDATEUOMCLASS_FAILURE = "UPDATEUOMCLASS_FAILURE";

//delete

export const DELETE_UOM_REQUEST = "DELETE_UOM_REQUEST";
export const DELETE_UOM_SUCCESS = "DELETE_UOM_SUCCESS";
export const DELETE_UOM_FAILURE = "DELETE_UOM_FAILURE";

export const DELETE_UOMCLASS_REQUEST = "DELETE_UOMCLASS_REQUEST";
export const DELETE_UOMCLASS_SUCCESS = "DELETE_UOMCLASS_SUCCESS";
export const DELETE_UOMCLASS_FAILURE = "DELETE_UOMCLASS_FAILURE";

//seach
export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";

export const FETCH_CUSTOM_REQUEST = "FETCH_CUSTOM_REQUEST";
export const FETCH_CUSTOM_SUCCESS = "FETCH_CUSTOM_SUCCESS";
export const FETCH_CUSTOM_FAILURE = "FETCH_CUSTOM_FAILURE";

//

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE";

export const FETCH_ROUTES_REQUEST = "FETCH_ROUTES_REQUEST";
export const FETCH_ROUTES_SUCCESS = "FETCH_ROUTES_SUCCESS";
export const FETCH_ROUTES_FAILURE = "FETCH_ROUTES_FAILURE";

export const FETCH_PARENT_CATEGORY_REQUEST = "FETCH_PARENT_CATEGORY_REQUEST";
export const FETCH_PARENT_CATEGORY_SUCCESS = "FETCH_PARENT_CATEGORY_SUCCESS";
export const FETCH_PARENT_CATEGORY_FAILURE = "FETCH_PARENT_CATEGORY_FAILURE";

export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

//step2

export const FETCH_ATTRIBUTE_REQUEST = "FETCH_ATTRIBUTE_REQUEST";
export const FETCH_ATTRIBUTE_SUCCESS = "FETCH_ATTRIBUTE_SUCCESS";
export const FETCH_ATTRIBUTE_FAILURE = "FETCH_ATTRIBUTE_FAILURE";

export const CREATE_ATTRIBUTE_REQUEST = "CREATE_ATTRIBUTE_REQUEST";
export const CREATE_ATTRIBUTE_SUCCESS = "CREATE_ATTRIBUTE_SUCCESS";
export const CREATE_ATTRIBUTE_FAILURE = "CREATE_ATTRIBUTE_FAILURE";

export const FETCH_PROPERTY_REQUEST = "FETCH_PROPERTY_REQUEST";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY_SUCCESS";
export const FETCH_PROPERTY_FAILURE = "FETCH_PROPERTY_FAILURE";

export const CREATE_PROPERTY_REQUEST = "CREATE_PROPERTY_REQUEST";
export const CREATE_PROPERTY_SUCCESS = "CREATE_PROPERTY_SUCCESS";
export const CREATE_PROPERTY_FAILURE = "CREATE_PROPERTY_FAILURE";

export const CREATE_VARIANT_REQUEST = "CREATE_VARIANT_REQUEST";
export const CREATE_VARIANT_SUCCESS = "CREATE_VARIANT_SUCCESS";
export const CREATE_VARIANT_FAILURE = "CREATE_VARIANT_FAILURE";
//step 3

export const CHECK_MRP_REQUEST = "CHECK_MRP_REQUEST";
export const CHECK_MRP_SUCCESS = "CHECK_MRP_SUCCESS";
export const CHECK_MRP_FAILURE = "CHECK_MRP_FAILURE";

export const FETCH_VENDOR_REQUEST = "FETCH_VENDOR_REQUEST";
export const FETCH_VENDOR_SUCCESS = "FETCH_VENDOR_SUCCESS";
export const FETCH_VENDOR_FAILURE = "FETCH_VENDOR_FAILURE";

export const FETCH_SHIPPINGPARTNER_REQUEST = "FETCH_SHIPPINGPARTNER_REQUEST";
export const FETCH_SHIPPINGPARTNER_SUCCESS = "FETCH_SHIPPINGPARTNER_SUCCESS";
export const FETCH_SHIPPINGPARTNER_FAILURE = "FETCH_SHIPPINGPARTNER_FAILURE";

export const FETCH_SHIPPINGPARTNERVIEW_REQUEST =
  "FETCH_SHIPPINGPARTNERVIEW_REQUEST";
export const FETCH_SHIPPINGPARTNERVIEW_SUCCESS =
  "FETCH_SHIPPINGPARTNERVIEW_SUCCESS";
export const FETCH_SHIPPINGPARTNERVIEW_FAILURE =
  "FETCH_SHIPPINGPARTNERVIEW_FAILURE";

export const FETCH_PRODUCTPACKAGE_REQUEST = "FETCH_PRODUCTPACKAGE_REQUEST";
export const FETCH_PRODUCTPACKAGE_SUCCESS = "FETCH_PRODUCTPACKAGE_SUCCESS";
export const FETCH_PRODUCTPACKAGE_FAILURE = "FETCH_PRODUCTPACKAGE_FAILURE";

export const FETCH_VENDORPRICELIST_REQUEST = "FETCH_VENDORPRICELIST_REQUEST";
export const FETCH_VENDORPRICELIST_SUCCESS = "FETCH_VENDORPRICELIST_SUCCESS";
export const FETCH_VENDORPRICELIST_FAILURE = "FETCH_VENDORPRICELIST_FAILURE";

export const CREATE_VP_REQUEST = "CREATE_VP_REQUEST";
export const CREATE_VP_SUCCESS = "CREATE_VP_SUCCESS";
export const CREATE_VP_FAILURE = "CREATE_VP_FAILURE";
//

//ProductsView

export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

//

//ProductsEdit

export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const EDIT_VARIANT_IMAGES_REQUEST = "EDIT_VARIANT_IMAGES_REQUEST";
export const EDIT_VARIANT_IMAGES_SUCCESS = "EDIT_VARIANT_IMAGES_SUCCESS";
export const EDIT_VARIANT_IMAGES_FAILURE = "EDIT_VARIANT_IMAGES_FAILURE";

//

export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_FAILURE = "FETCH_COUNTRY_FAILURE";

export const GET_PRODUCT_ID = "GET_PRODUCT_ID";

export const FETCH_PRODUCT_BY_ID_REQUEST = "FETCH_PRODUCT_BY_ID_REQUEST";
export const FETCH_PRODUCT_BY_ID_SUCCESS = "FETCH_PRODUCT_BY_ID_SUCCESS";
export const FETCH_PRODUCT_BY_ID_FAILURE = "FETCH_PRODUCT_BY_ID_FAILURE";

export const FETCH_STATE_FAILURE = "FETCH_STATE_FAILURE";
export const FETCH_STATE = "FETCH_STATE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const FAVOURITE_PRODUCT_REQUEST = "FAVOURITE_PRODUCT_REQUEST";
export const FAVOURITE_PRODUCT_SUCCESS = "FAVOURITE_PRODUCT_SUCCESS";
export const FAVOURITE_PRODUCT_FAILURE = "FAVOURITE_PRODUCT_FAILURE";
//search redux

export const FETCH_CURRENCY_REQUEST = "FETCH_CURRENCY_REQUEST";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAILURE = "FETCH_CURRENCY_FAILURE";

//session
export const GET_SESSION_ID = "GET_SESSION_ID";
export const GET_TOKEN_SUCCESSS = "GET_TOKEN_SUCCESSS";

export const FETCH_ACCESS_MANAGEMENT_REQUEST="FETCH_ACCESS_MANAGEMENT_REQUEST";
export const FETCH_ACCESS_MANAGEMENT_SUCCESS="FETCH_ACCESS_MANAGEMENT_SUCCESS";
export const FETCH_ACCESS_MANAGEMENT_FAILURE="FETCH_ACCESS_MANAGEMENT_FAILURE";


/*			
Copyright (C) 2022 Eunimart Omnichannel Pvt Ltd. (www.eunimart.com)			
All rights reserved.			
This program is free software: you can redistribute it and/or modify			
it under the terms of the GNU General Public License as published by			
the Free Software Foundation, either version 3 of the License, or			
(at your option) any later version.			
This program is distributed in the hope that it will be useful,			
but WITHOUT ANY WARRANTY; without even the implied warranty of			
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the			
GNU General Public License for more details.			
You should have received a copy of the GNU General Public License			
along with this program. If not, see <http://www.gnu.org/licenses/>.			
*/