
export const  GET_SALES_RETUNS_LIST_REQUEST = "GET_SALES_RETUNS_LIST_REQUEST";
export const  GET_SALES_RETUNS_LIST_SUCCESS = "GET_SALES_RETUNS_LIST_SUCCESS";
export const  GET_SALES_RETUNS_LIST_FAILURE = "GET_SALES_RETUNS_LIST_FAILURE";


export const  GET_CONTACT_LIST_REQUEST = "GET_CONTACT_LIST_REQUEST";
export const  GET_CONTACT_LIST_SUCCESS = "GET_CONTACT_LIST_SUCCESS";
export const  GET_CONTACT_LIST_FAILURE = "GET_CONTACT_LIST_FAILURE";

export const  GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const  GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS ";
export const  GET_PRODUCT_LIST_FAILURE = "GET_PRODUCT_LIST_FAILURE";

export const  SEARCH_PRODUCT_LIST_REQUEST = "SEARCH_PRODUCT_LIST_REQUEST";
export const  SEARCH_PRODUCT_LIST_SUCCESS = "SEARCH_PRODUCT_LIST_SUCCESS ";
export const  SEARCH_PRODUCT_LIST_FAILURE = "SEARCH_PRODUCT_LIST_FAILURE";

export const  DELETE_SALES_RETURNS_REQUEST = "DELETE_SALES_RETURNS_REQUEST";
export const  DELETE_SALES_RETURNS_SUCCESS = "DELETE_SALES_RETURNS_SUCCESS ";
export const  DELETE_SALES_RETURNS_FAILURE = "DELETE_SALES_RETURNS_FAILURE";

export const  SR_EMAIL_REQUEST = "SR_EMAIL_REQUEST";
export const  SR_EMAIL_SUCCESS = "SR_EMAIL_SUCCESS ";
export const  SR_EMAIL_FAILURE = "SR_EMAIL_FAILURE";

export const  PRINT_PDF_REQUEST = "PRINT_PDF_REQUEST";
export const  PRINT_PDF_SUCCESS = "PRINT_PDF_SUCCESS ";
export const  PRINT_PDF_FAILURE = "PRINT_PDF_FAILURE";

export const  GENERATE_PDF_REQUEST = "GENERATE_PDF_REQUEST";
export const  GENERATE_PDF_SUCCESS = "GENERATE_PDF_SUCCESS ";
export const  GENERATE_PDF_FAILURE = "GENERATE_PDF_FAILURE";

export const  ISSUE_DEBIT_NOTE_REQUEST = "ISSUE_DEBIT_NOTE_REQUEST";
export const  ISSUE_DEBIT_NOTE_SUCCESS = "ISSUE_DEBIT_NOTE_SUCCESS ";
export const  ISSUE_DEBIT_NOTE_FAILURE = "ISSUE_DEBIT_NOTE_FAILURE";

export const  ISSUE_CREDIT_NOTE_REQUEST = "ISSUE_CREDIT_NOTE_REQUEST";
export const  ISSUE_CREDIT_NOTE_SUCCESS = "ISSUE_CREDIT_NOTE_SUCCESS ";
export const  ISSUE_CREDIT_NOTE_FAILURE = "ISSUE_CREDIT_NOTE_FAILURE";

export const  MARK_AS_ACTIVE_REQUEST = "MARK_AS_ACTIVE_REQUEST";
export const  MARK_AS_ACTIVE_SUCCESS = "MARK_AS_ACTIVE_SUCCESS ";
export const  MARK_AS_ACTIVE_FAILURE = "MARK_AS_ACTIVE_FAILURE";

export const  MARK_AS_RECIVED_REQUEST = "MARK_AS_RECIVED_REQUEST";
export const  MARK_AS_RECIVED_SUCCESS = "MARK_AS_RECIVED_SUCCESS ";
export const  MARK_AS_RECIVED_FAILURE = "MARK_AS_RECIVED_FAILURE";

export const  GET_VIEW_SALES_RETUNS_REQUEST = "GET_VIEW_SALES_RETUNS_REQUEST";
export const  GET_VIEW_SALES_RETUNS_SUCCESS = "GET_VIEW_SALES_RETUNS_SUCCESS ";
export const  GET_VIEW_SALES_RETUNS_FAILURE = "GET_VIEW_SALES_RETUNS_FAILURE";

export const  GET_SALES_RETUNS_ID_REQUEST = "GET_SALES_RETUNS_ID_REQUEST";
export const  GET_SALES_RETUNS_ID_SUCCESS = "GET_SALES_RETUNS_ID_SUCCESS ";
export const  GET_SALES_RETUNS_ID_FAILURE = "GET_SALES_RETUNS_ID_FAILURE";

export const  GET_RETUN_REASON_REQUEST = "GET_RETUN_REASON_REQUEST";
export const  GET_RETUN_REASON_SUCCESS = "GET_RETUN_REASON_SUCCESS ";
export const  GET_RETUN_REASON_FAILURE = "GET_RETUN_REASON_FAILURE";

export const  GET_SALES_RETUNS_CURRENCY_REQUEST = "GET_SALES_RETUNS_CURRENCY_REQUEST";
export const  GET_SALES_RETUNS_CURRENCY_SUCCESS = "GET_SALES_RETUNS_CURRENCY_SUCCESS ";
export const  GET_SALES_RETUNS_CURRENCY_FAILURE = "GET_SALES_RETUNS_CURRENCY_FAILURE";

export const  GET_SHIPPING_LIST_REQUEST = "GET_SHIPPING_LIST_REQUEST";
export const  GET_SHIPPING_LIST_SUCCESS = "GET_SHIPPING_LIST_SUCCESS ";
export const  GET_SHIPPING_LIST_FAILURE = "GET_SHIPPING_LIST_FAILURE";

export const  FETCH_SALES_ORDER_REQUEST = "FETCH_SALES_ORDER_REQUEST";
export const  FETCH_SALES_ORDER_SUCCESS = "FETCH_SALES_ORDER_SUCCESS ";
export const  FETCH_SALES_ORDER_FAILURE = "FETCH_SALES_ORDER_FAILURE";

export const  CREATE_SALES_RETURNS_REQUEST = "CREATE_SALES_RETURNS_REQUEST";
export const  CREATE_SALES_RETURNS_SUCCESS = "CREATE_SALES_RETURNS_SUCCESS ";
export const  CREATE_SALES_RETURNS_FAILURE = "CREATE_SALES_RETURNS_FAILURE";

export const  EDIT_SALES_RETURNS_REQUEST = "EDIT_SALES_RETURNS_REQUEST";
export const  EDIT_SALES_RETURNS_SUCCESS = "EDIT_SALES_RETURNS_SUCCESS";
export const  EDIT_SALES_RETURNS_FAILURE = "EDIT_SALES_RETURNS_FAILURE";


export const ESTIMATED_COST_SUCCESS="ESTIMATED_COST_SUCCESS";
export const ESTIMATED_COST_FAILURE="ESTIMATED_COST_FAILURE";

export const GET_TOKEN_SUCCESSS = "GET_TOKEN_SUCCESSS";

export const RATE_CALCULATOR_REQUEST="RATE_CALCULATOR_REQUEST";
export const RATE_CALCULATOR_SUCCESS="RATE_CALCULATOR_SUCCESS";
export const RATE_CALCULATOR_FAILURE="RATE_CALCULATOR_FAILURE";


//Products list 
export const FETCH_PRODUCTS_DATA_SUCCESS = "FETCH_PRODUCTS_DATA_SUCCESS";
export const FETCH_PRODUCTS_DATA_FAILURE = "FETCH_PRODUCTS_DATA_FAILURE";


export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";


//UOM
export const FETCH_UOM_SUCCESS="FETCH_UOM_SUCCESS";
export const FETCH_UOM_FAILURE="FETCH_UOM_FAILURE";

export const STATES_SUCCESS = "STATES_SUCCESS";
export const STATES_FAILURE = "STATES_FAILURE";

export const COUNTRIES_SUCCESS = "COUNTRIES_SUCCESS";
export const COUNTRIES_FAILURE = "COUNTRIES_FAILURE";



export const FETCH_RETURN_TYPE_SUCCESS = "FETCH_RETURN_TYPE_SUCCESS";
export const FETCH_RETURN_TYPE_FAILURE = "FETCH_RETURN_TYPE_FAILURE";

export const GET_DOCUMENT_TYPE_REQUEST = "GET_DOCUMENT_TYPE_REQUEST";
export const GET_DOCUMENT_TYPE_SUCCESS = "GET_DOCUMENT_TYPE_SUCCESS";
export const GET_DOCUMENT_TYPE_FAILURE = "GET_DOCUMENT_TYPE_FAILURE";

export const FETCH_SEARCH_SOURCE_DOCUMENT_DATA_SUCCESS="FETCH_SEARCH_SOURCE_DOCUMENT_DATA_SUCCESS";
export const FETCH_SEARCH_SOURCE_DOCUMENT_DATA_FAILURE="FETCH_SEARCH_SOURCE_DOCUMENT_DATA_FAILURE";

export const DOCUMENT_DATA_SUCCESS="DOCUMENT_DATA_SUCCESS";
export const DOCUMENT_DATA_FAILURE="DOCUMENT_DATA_FAILURE";

export const ACCESS_MANAGEMENT_SUCCESS="ACCESS_MANAGEMENT_SUCCESS";
export const ACCESS_MANAGEMENT_FAIL="ACCESS_MANAGEMENT_FAIL";

//Credit NOte Tab
export const GET_CREDIT_NOTE_LIST_REQUEST = "GET_CREDIT_NOTE_LIST_REQUEST";
export const GET_CREDIT_NOTE_LIST_SUCCESS = "GET_CREDIT_NOTE_LIST_SUCCESS";
export const GET_CREDIT_NOTE_LIST_FAILURE = "GET_CREDIT_NOTE_LIST_FAILURE";


/*
 Copyright (C) 2022 Eunimart Omnichannel Pvt Ltd. (www.eunimart.com)
 All rights reserved.
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License v3.0 as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License v3.0 for more details.
 You should have received a copy of the GNU Lesser General Public License v3.0
 along with this program.  If not, see <https://www.gnu.org/licenses/lgpl-3.0.html/>.
*/